# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(511, 362)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(80, 90, 331, 221))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.userTableWidget = QtWidgets.QTableWidget(self.tab)
        self.userTableWidget.setGeometry(QtCore.QRect(0, 0, 331, 161))
        self.userTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.userTableWidget.setColumnCount(5)
        self.userTableWidget.setObjectName("userTableWidget")
        self.userTableWidget.setRowCount(0)
        self.userTableWidget.horizontalHeader().setDefaultSectionSize(65)
        self.deleteUserButton = QtWidgets.QPushButton(self.tab)
        self.deleteUserButton.setGeometry(QtCore.QRect(120, 160, 91, 31))
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.itemTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.itemTableWidget.setGeometry(QtCore.QRect(0, 0, 331, 161))
        self.itemTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.itemTableWidget.setColumnCount(4)
        self.itemTableWidget.setObjectName("itemTableWidget")
        self.itemTableWidget.setRowCount(0)
        self.itemTableWidget.horizontalHeader().setDefaultSectionSize(82)
        self.deleteItemButton = QtWidgets.QPushButton(self.tab_2)
        self.deleteItemButton.setGeometry(QtCore.QRect(120, 160, 91, 31))
        self.deleteItemButton.setObjectName("deleteItemButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.errorLabel = QtWidgets.QLabel(Dialog)
        self.errorLabel.setGeometry(QtCore.QRect(90, 320, 311, 21))
        self.errorLabel.setObjectName("errorLabel")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Admin"))
        self.deleteUserButton.setText(_translate("Dialog", "Delete User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "User"))
        self.deleteItemButton.setText(_translate("Dialog", "Delete Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Item"))
        self.errorLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
