# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(537, 500)
        self.horizontalLayoutWidget = QtWidgets.QWidget(login_window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 190, 281, 106))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.emailLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_2.addWidget(self.emailLabel)
        self.passwdLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.passwdLabel.setFont(font)
        self.passwdLabel.setObjectName("passwdLabel")
        self.verticalLayout_2.addWidget(self.passwdLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.emailLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.verticalLayout.addWidget(self.emailLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.errorLabel = QtWidgets.QLabel(login_window)
        self.errorLabel.setGeometry(QtCore.QRect(150, 300, 241, 21))
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(login_window)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(210, 330, 111, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_3.addWidget(self.loginButton)
        self.goToRegisterButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.goToRegisterButton.setFont(font)
        self.goToRegisterButton.setObjectName("goToRegisterButton")
        self.verticalLayout_3.addWidget(self.goToRegisterButton)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Login"))
        self.emailLabel.setText(_translate("login_window", "<html><head/><body><p align=\"center\">Email</p></body></html>"))
        self.passwdLabel.setText(_translate("login_window", "<html><head/><body><p align=\"center\">Password</p></body></html>"))
        self.errorLabel.setText(_translate("login_window", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.loginButton.setText(_translate("login_window", "Login"))
        self.goToRegisterButton.setText(_translate("login_window", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QDialog()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
