# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(230, 0, 331, 61))
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 50, 521, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.itemTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.itemTableWidget.setGeometry(QtCore.QRect(50, 90, 701, 371))
        self.itemTableWidget.setLineWidth(1)
        self.itemTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.itemTableWidget.setRowCount(0)
        self.itemTableWidget.setColumnCount(4)
        self.itemTableWidget.setObjectName("itemTableWidget")
        self.itemTableWidget.horizontalHeader().setDefaultSectionSize(170)
        self.itemTableWidget.verticalHeader().setDefaultSectionSize(50)
        self.publishItemButton = QtWidgets.QPushButton(self.centralwidget)
        self.publishItemButton.setGeometry(QtCore.QRect(580, 470, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.publishItemButton.setFont(font)
        self.publishItemButton.setObjectName("publishItemButton")
        self.adminPanelButton = QtWidgets.QPushButton(self.centralwidget)
        self.adminPanelButton.setEnabled(False)
        self.adminPanelButton.setVisible(False)
        self.adminPanelButton.setGeometry(QtCore.QRect(340, 470, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.adminPanelButton.setFont(font)
        self.adminPanelButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.adminPanelButton.setObjectName("adminPanelButton")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(650, 520, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.logoutButton.setFont(font)
        self.logoutButton.setObjectName("logoutButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Welcome !</span></p></body></html>"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "search products..."))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.publishItemButton.setText(_translate("MainWindow", "Publish Products"))
        self.adminPanelButton.setText(_translate("MainWindow", "AdminPanel"))
        self.logoutButton.setText(_translate("MainWindow", "Log Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
