# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/publish_item_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PublishItem(object):
    def setupUi(self, PublishItem):
        PublishItem.setObjectName("PublishItem")
        PublishItem.resize(559, 422)
        self.errorLabel = QtWidgets.QLabel(PublishItem)
        self.errorLabel.setGeometry(QtCore.QRect(90, 310, 371, 31))
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(PublishItem)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 90, 411, 211))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.descriptionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.priceLavel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.priceLavel.setObjectName("priceLavel")
        self.verticalLayout.addWidget(self.priceLavel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.titleLineEdit.setFont(font)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.verticalLayout_2.addWidget(self.titleLineEdit)
        self.descriptionTextEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout_2.addWidget(self.descriptionTextEdit)
        self.priceDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.priceDoubleSpinBox.setDecimals(1)
        self.priceDoubleSpinBox.setMaximum(100000.0)
        self.priceDoubleSpinBox.setProperty("value", 100000.0)
        self.priceDoubleSpinBox.setObjectName("priceDoubleSpinBox")
        self.verticalLayout_2.addWidget(self.priceDoubleSpinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.submitButton = QtWidgets.QPushButton(PublishItem)
        self.submitButton.setGeometry(QtCore.QRect(200, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")

        self.retranslateUi(PublishItem)
        QtCore.QMetaObject.connectSlotsByName(PublishItem)

    def retranslateUi(self, PublishItem):
        _translate = QtCore.QCoreApplication.translate
        PublishItem.setWindowTitle(_translate("PublishItem", "Submit"))
        self.errorLabel.setText(_translate("PublishItem", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titleLabel.setText(_translate("PublishItem", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Title</span></p></body></html>"))
        self.descriptionLabel.setText(_translate("PublishItem", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Description</span></p></body></html>"))
        self.priceLavel.setText(_translate("PublishItem", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Price</span></p></body></html>"))
        self.submitButton.setText(_translate("PublishItem", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PublishItem = QtWidgets.QDialog()
    ui = Ui_PublishItem()
    ui.setupUi(PublishItem)
    PublishItem.show()
    sys.exit(app.exec_())
