# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/register_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerDialog(object):
    def setupUi(self, registerDialog):
        registerDialog.setObjectName("registerDialog")
        registerDialog.resize(548, 493)
        self.horizontalLayoutWidget = QtWidgets.QWidget(registerDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 90, 391, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.emailLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.emailLabel.setFont(font)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout.addWidget(self.emailLabel)
        self.passwdLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.passwdLabel.setFont(font)
        self.passwdLabel.setObjectName("passwdLabel")
        self.verticalLayout.addWidget(self.passwdLabel)
        self.passwdLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.passwdLabel_2.setFont(font)
        self.passwdLabel_2.setObjectName("passwdLabel_2")
        self.verticalLayout.addWidget(self.passwdLabel_2)
        self.nicknameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nicknameLabel.setFont(font)
        self.nicknameLabel.setObjectName("nicknameLabel")
        self.verticalLayout.addWidget(self.nicknameLabel)
        self.contantInfoLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.contantInfoLabel.setFont(font)
        self.contantInfoLabel.setObjectName("contantInfoLabel")
        self.verticalLayout.addWidget(self.contantInfoLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.emailLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.verticalLayout_2.addWidget(self.emailLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout_2.addWidget(self.passwordLineEdit)
        self.confirmPasswordLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.confirmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordLineEdit.setObjectName("confirmPasswordLineEdit")
        self.verticalLayout_2.addWidget(self.confirmPasswordLineEdit)
        self.nicknameEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.nicknameEdit.setObjectName("nicknameEdit")
        self.verticalLayout_2.addWidget(self.nicknameEdit)
        self.contactInfoEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.contactInfoEdit.setObjectName("contactInfoEdit")
        self.verticalLayout_2.addWidget(self.contactInfoEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.errorLabel = QtWidgets.QLabel(registerDialog)
        self.errorLabel.setGeometry(QtCore.QRect(90, 340, 391, 41))
        self.errorLabel.setObjectName("errorLabel")
        self.registerButton = QtWidgets.QPushButton(registerDialog)
        self.registerButton.setGeometry(QtCore.QRect(220, 380, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")

        self.retranslateUi(registerDialog)
        QtCore.QMetaObject.connectSlotsByName(registerDialog)

    def retranslateUi(self, registerDialog):
        _translate = QtCore.QCoreApplication.translate
        registerDialog.setWindowTitle(_translate("registerDialog", "Register"))
        self.emailLabel.setText(_translate("registerDialog", "<html><head/><body><p align=\"center\">Your email</p></body></html>"))
        self.passwdLabel.setText(_translate("registerDialog", "<html><head/><body><p align=\"center\">Password</p></body></html>"))
        self.passwdLabel_2.setText(_translate("registerDialog", "<html><head/><body><p align=\"center\">Repet Password</p></body></html>"))
        self.nicknameLabel.setText(_translate("registerDialog", "<html><head/><body><p align=\"center\">NickName</p></body></html>"))
        self.contantInfoLabel.setText(_translate("registerDialog", "<html><head/><body><p align=\"center\">Contant Info</p></body></html>"))
        self.errorLabel.setText(_translate("registerDialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.registerButton.setText(_translate("registerDialog", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerDialog = QtWidgets.QDialog()
    ui = Ui_registerDialog()
    ui.setupUi(registerDialog)
    registerDialog.show()
    sys.exit(app.exec_())
